// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type HelloReply struct {
	Message string `json:"message"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Order struct {
	ID           *string        `json:"id"`
	CustomerID   *string        `json:"customerID"`
	OrderDetails []*OrderDetail `json:"orderDetails"`
}

type OrderDetail struct {
	ID        *string `json:"id"`
	OrderID   *string `json:"orderID"`
	MenuName  *string `json:"menuName"`
	MenuPrice *int    `json:"menuPrice"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
